### ISSUE TITLE
Small accuracy deviations

### ISSUE THREAD

**Issue by Shoichi-Ebata** [Sensirion/arduino-i2c-sdp#3]
startContinuousMeasurementWithMassFlowTComp()
>Small accuracy deviations (few % of reading) can occur during the next 12ms.

Are small accuracy deviations (a few percent of the reading) included in the values for Zero Point Accuracy and Span Accuracy in the sensor's datasheet?

**Comment by LeonieFierz** [comment]
Hi @Shoichi-Ebata 

The measurements are within the specified values in the datasheet 20ms (8ms until you get the first reading + 12ms with lower accuracy) after you sent the startContinuousMeasurementWithMassFlowTComp() command, before the deviation of a few % of the reading might occur.

Best, Léonie

**Comment by Shoichi-Ebata** [comment]
Hi Léonie,

Thank you for the information. I understand.

Best regards,
Shoichi
